sonar.projectKey=kevcordier_Deck-Legacy
sonar.organization=kevcordier
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sources = src
sonar.tests = tests
sonar.coverage.exclusions=src/pages/**,src/components/**,src/contexts/**,coverage/**,src/hooks/**,src/data/**,src/engine/infrastructure/**,src/main.tsx,src/App.tsx
sonar.duplicate.exclusions=src/data/**
