name: Code quality checks and tests

on:
  workflow_call:

jobs:
  ci:
    name: CI
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: 🏗️ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: ⚙️ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile
      - name: 📝 Lint
        run: pnpm lint
      - name: 🔍 Typecheck
        run: pnpm typecheck
      - name: 🎨 Format check
        run: pnpm format:check
      - name: 🧪 Tests
        run: pnpm test:coverage
      - name: 📊 Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c
        with:
          threshold-icons: "{0: '🔴', 80: '🟠', 90: '🟢'}"
